# Generated by Django 4.2.20 on 2025-05-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginasweb", "0002_controlador_leitura_regra_sensor_tiposensor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiposensor",
            name="numero_serial",
            field=models.CharField(
                default="xxxxx", max_length=255, verbose_name="Número Serial"
            ),
            preserve_default=False,
        ),
    ]
