# Generated by Django 3.2.25 on 2025-05-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0004_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlador',
            name='cadastro_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paginasweb.cadastro'),
        ),
        migrations.AddField(
            model_name='controlador',
            name='nome',
            field=models.CharField(default='Controlador Padrão', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-mail'),
        ),
    ]
