# Generated by Django 4.2.20 on 2025-05-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paginasweb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Controlador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.FloatField()),
                ("data", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Regra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "horario_inicio",
                    models.CharField(max_length=10, verbose_name="Horário de Início"),
                ),
                (
                    "horario_fim",
                    models.CharField(max_length=10, verbose_name="Horário de Fim"),
                ),
                ("valor_minimo", models.FloatField()),
                ("valor_maximo", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "controlador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginasweb.controlador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="curso",
            name="campus",
        ),
        migrations.RemoveField(
            model_name="historico",
            name="solicitacao",
        ),
        migrations.RemoveField(
            model_name="historico",
            name="status",
        ),
        migrations.DeleteModel(
            name="Servidor",
        ),
        migrations.RemoveField(
            model_name="solicitacao",
            name="curso",
        ),
        migrations.RemoveField(
            model_name="solicitacao",
            name="solicitado_por",
        ),
        migrations.RemoveField(
            model_name="solicitacao",
            name="tipo_solicitação",
        ),
        migrations.DeleteModel(
            name="Aluno",
        ),
        migrations.DeleteModel(
            name="Campus",
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
        migrations.DeleteModel(
            name="Historico",
        ),
        migrations.DeleteModel(
            name="Solicitacao",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.DeleteModel(
            name="TipoSolicitacao",
        ),
        migrations.AddField(
            model_name="sensor",
            name="tipo_sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="paginasweb.tiposensor"
            ),
        ),
        migrations.AddField(
            model_name="regra",
            name="tipo_sensor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="paginasweb.tiposensor",
            ),
        ),
        migrations.AddField(
            model_name="leitura",
            name="alerta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="paginasweb.regra",
            ),
        ),
        migrations.AddField(
            model_name="leitura",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="paginasweb.sensor"
            ),
        ),
        migrations.AddField(
            model_name="leitura",
            name="tipo_sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="paginasweb.tiposensor"
            ),
        ),
    ]
