# Generated by Django 4.2.20 on 2025-06-05 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("paginasweb", "0005_auto_20250528_2205"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastro",
            name="cadastrado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
