# Generated by Django 4.2.20 on 2025-06-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginasweb", "0006_cadastro_cadastrado_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="cadastrado_em",
            field=models.DateTimeField(auto_now_add=True, max_length=30),
        ),
    ]
